### PR TITLE
minify, fixes, beautify.

### PR DESCRIPTION
**Pull request by utf-4096**
- Fixed the "protected" keyword in strict mode
- const can break some things when code is executed another time
- Added minified code, think of doing it in the future ( https://jscompress.com/ )
- Beautified the code to improve visibility

### CODE REVIEW

**Comment by speedyplane2247** [comment]
You want to improve readability, so you minify it?

**Comment by utf-4096** [comment]
i said "added minified code" i didnt say "overwrite"

**Comment by dakrk** [comment]
ok

**Comment by dakrk** [comment]
ok

**Comment by dakrk** [comment]
ok

**Comment by dakrk** [comment]
ok

**Comment by dakrk** [comment]
ok

**Comment by dakrk** [comment]
ok

**Comment by dakrk** [comment]
ok

**Comment by dakrk** [comment]
# _**ok**_

**Comment by 1024x2** [comment]
what the fuck

**Comment by 1024x2** [comment]
Congrats, you added nothing useful to pkg93!
You deserve an award!

**Pull request closed without merging**
